### ISSUE TITLE
字符串概述

### ISSUE THREAD

**Issue by Hu-Xinyu** [dstcxxxz/Learn#6]
## 字符串概述
> String 类代表字符串。Java 程序中的所有字符串字面值（如 "abc" ）都作为此类的实例实现。
> 字符串是常量；它们的值在创建之后不能更改。字符串缓冲区支持可变的字符串。因为 String 对象是不可变的，所以可以共享。

- String类已实现的接口有Serializable、Comparable`<String>`、CharSequence。
- String类中存在一个常量字符数组：private final char value[];
- String类中存在一个hash变量：private int hash;//默认为0

### 特点
- String类是常量类，所有它有没子类，一旦被初始化后不可以被改变。
- “abc”和new String("abc")的最大区别：前者在内存中有一个对象，后者在内存中有两个对象。
- ==和equals：String类复写了Object类的equals方法，用于判断字符串是否相等，而不是比较内存地址值

### 小知识点
JVM中常量池存在于方法区，字符串常量池在java1.6和java1.7后是不同的，1.6之前字符串常量池是存在于方法区的，而在1.7后，hotspot把字符串常量池移出了方法区放入堆中，具体可由intern()方法检测。

**Comment by LiHuaYang** [comment]
关于 JDK6 和 JDK6 以后的字符串常量池可以讲一下
